apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: no-htcjob-argo-example-
spec:
  entrypoint: wf
  volumeClaimTemplates:
  - metadata:
      name: vol-cephfs-h2t
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: csi-cephfs-storageclass
  templates:
  - name: wf
    steps:
    - - name: clear
        template: clear
    - - name: unzip
        template: unzip
    - - name: dl-samples
        template: dl-samples
    - - name: skim
        template: skim
    - - name: hist
        template: hist
    - - name: plot
        template: plot
  - name: clear
    script:
      image: alpine
      volumeMounts:
      - mountPath: /data/
        name: vol-cephfs-h2t
      command: [sh]
      source: |
        rm -rf /data/ht2/payload-reg &&
        mkdir -p /data/ht2/
  - name: unzip
    script:
      image: kubeless/unzip
      volumeMounts:
      - mountPath: /data/
        name: vol-cephfs-h2t
      command: [bash]
      source: |
        curl -OL https://github.com/awesome-workshop/payload/archive/master.zip &&
        unzip master.zip &&
        mv payload-master /data/ht2/payload-reg
  - name: dl-samples
    script:
      image: xkxgygmoqkguuddnkz/root1804
      volumeMounts:
      - mountPath: /data/
        name: vol-cephfs-h2t
      command: [sh]
      source: |
        cd /data/ht2/payload-reg/ &&
        mkdir samples &&
        sh download.sh samples/
  - name: skim
    script:
      image: xkxgygmoqkguuddnkz/root1804
      volumeMounts:
      - mountPath: /data/
        name: vol-cephfs-h2t
      command: [bash]
      source: |
        cd /data/ht2/payload-reg/ &&
        mkdir skims &&
        bash skim.sh samples/ skims/
  - name: hist
    script:
      image: xkxgygmoqkguuddnkz/root1804 # 'rootproject/root-conda:6.18.04' has root v20.00, had to make my own img
      volumeMounts:
      - mountPath: /data/
        name: vol-cephfs-h2t
      command: [bash]
      source: |
        cd /data/ht2/payload-reg/ &&
        mkdir histograms &&
        bash histograms.sh skims/ histograms/
  - name: plot
    script:
      image: xkxgygmoqkguuddnkz/root1804 # 'rootproject/root-conda:6.18.04' has root v20.00, had to make my own img
      volumeMounts:
      - mountPath: /data/
        name: vol-cephfs-h2t
      command: [bash]
      source: |
        cd /data/ht2/payload-reg/ &&
        mkdir plots &&
        bash plot.sh histograms/histograms.root plots/
