stages:
  - compile
  - deploy
  - build

build_go_binary:
  stage: compile
  image: golang:1.13-buster
  script:
    - export GO111MODULE=on
    - go mod download
    - echo 'Building static go binary ...'
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/bin/receiver cloudevents/receiver.go
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/bin/sender cloudevents/sender.go
  artifacts:
    paths:
      - build

deploy_to_s3:
  stage: deploy
  image:
      name: jess/s3cmd
      entrypoint: [""]
  script:
    - s3cmd --access_key ${S3_ACCESS_KEY} --secret_key ${S3_SECRET_KEY} --host s3.cern.ch --host-bucket "%(bucket)s.s3.cern.ch" put build/bin/receiver s3://TADO_BUCKET/receiver
    - s3cmd --access_key ${S3_ACCESS_KEY} --secret_key ${S3_SECRET_KEY} --host s3.cern.ch --host-bucket "%(bucket)s.s3.cern.ch" put build/bin/sender s3://TADO_BUCKET/sender
