apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: htc-watcher
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: htc-watcher
            image: gitlab-registry.cern.ch/clange/condorsubmit
            command: ["sh", "-c"]
            args: ["
              export CONDOR_USER=`cat /mnt/kinit/username` &&
              echo $CONDOR_USER &&
              useradd -Ms /bin/bash $CONDOR_USER &&
              mkdir -m 777 /scratch &&
              pip install s3cmd &&
              runuser -l $CONDOR_USER -c '
                cat /mnt/kinit/password| kinit &&
                cd /scratch &&
                export _condor_SCHEDD_HOST=bigbird10.cern.ch &&
                export _condor_CREDD_HOST=bigbird10.cern.ch && 
                s3cmd get -c /mnt/s3/.s3cfg s3://TADO_BUCKET/watcher &&
                s3cmd get -c /mnt/s3/.s3cfg s3://TADO_BUCKET/runCondorQ.py &&
                chmod 777 watcher &&
                ./watcher'
              "]
            volumeMounts:
            - name: "kinit-secret-vol"
              mountPath: "/mnt/kinit"
            - name: "s3cfg-cm-vol"
              mountPath: "/mnt/s3"
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: gitlab-registry
          volumes:
          - name: "kinit-secret-vol"
            secret:
              secretName: "kinit-secret"
          - name: "s3cfg-cm-vol"
            configMap:
              name: "s3cfg"
