apiVersion: htc.cern.ch/v1alpha1
kind: HTCJob
metadata:
  name: example-htcjob
spec:
  container: centos
  script: |
    #!/bin/bash
    echo "AAA"
    echo "BBB"
    echo CCC
    echo "JOB_NAME"
    echo $JOB_NAME
    echo "JOB_NAME"
