apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: htcjobs.htc.cern.ch
spec:
  group: htc.cern.ch
  names:
    kind: HTCJob
    listKind: HTCJobList
    plural: htcjobs
    singular: htcjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HTCJob is the Schema for the htcjobs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: //    Spec   HTCJobSpec   `json:"spec,omitempty"` //    Status
            HTCJobStatus `json:"status,omitempty"`
          properties:
            htcopts:
              type: string
            name:
              type: string
            queue:
              type: integer
            script:
              properties:
                command:
                  type: string
                image:
                  type: string
                source:
                  type: string
              required:
              - command
              - image
              - source
              type: object
          required:
          - name
          - script
          type: object
        status:
          properties:
            active:
              type: integer
            failed:
              type: integer
            jobid:
              items:
                type: string
              type: array
            succeeded:
              type: integer
            uniqid:
              type: integer
          required:
          - active
          - failed
          - succeeded
          - uniqid
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
