apiVersion: htc.cern.ch/v1alpha1
kind: HTCJob
metadata:
  name: example-htcjob
spec:
  name: xmpl-img
  script:
    image: centos
    command: ["bash"]
    source: |
      echo 'AAA'
      echo 'BBB'
      echo CCC
      echo 'JOB_NAME'
      echo $JOB_NAME
      echo $TEMP_DIR
      echo 'JOB_NAME'
