apiVersion: apps/v1
kind: Deployment
metadata:
  name: htc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: htc-operator
  template:
    metadata:
      labels:
        name: htc-operator
    spec:
      serviceAccountName: htc-operator
      containers:
        - name: htc-operator
          # Replace this with the built image name
          image: xkxgygmoqkguuddnkz/htc-operator
          command:
          - htc-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "htc-operator"
