apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cephfs-cms
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-cms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: htc-operator
  template:
    metadata:
      labels:
        name: htc-operator
    spec:
      serviceAccountName: htc-operator
      imagePullSecrets:
      - name: gitlab-registry
      containers:
        - name: htc-operator
          # Replace this with the built image name
          image: gitlab-registry.cern.ch/cms-cloud/htc-operator:latest
          command: ["sh", "-c"]
          args: [main]
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /secret/keytabvol
            name: keytab-secret-vol
          - mountPath: /data
            name: vol-cephfs-cms
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "htc-operator"
      volumes:
      - name: vol-cephfs-cms
        persistentVolumeClaim:
          claimName: pvc-cephfs-cms
          readOnly: false
      - name: keytab-secret-vol
        secret:
          secretName: kerberos-keytab-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloudevents-service
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    name: htc-operator
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloudevents-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "http"
spec:
  rules:
  - host: cms-batch-test.cern.ch
    http:
      paths:
      - path: /cloudevents
        backend:
          serviceName: cloudevents-service
          servicePort: 80
